spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
  datasource:
    url: jdbc:postgresql://34.64.238.77:5432/heregather
    username: right42
    password: right42
    platform: postgres