INSERT INTO REGION(REGION_ID, NAME, LEVEL) VALUES(1, 'TEST', 1);
INSERT INTO REGION(REGION_ID, NAME, LEVEL) VALUES(2, 'TEST2', 2);
INSERT INTO REGION(REGION_ID, NAME, LEVEL) VALUES(3, 'TEST3', 3);

INSERT INTO INTEREST(INTEREST_ID, NAME) VALUES(1, '관심사1');
INSERT INTO INTEREST(INTEREST_ID, NAME) VALUES(2, '관심사2');
INSERT INTO INTEREST(INTEREST_ID, NAME) VALUES(3, '관심사3');
INSERT INTO INTEREST(INTEREST_ID, NAME) VALUES(4, '관심사4');